
server:
  address: 0.0.0.0
  port: 8103 # 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxxxx:3306/medai?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    username: xxxxx
#    password: xxxxx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medai
    username: root
    password: 1123
  # session 失效时间 30 天
  session:
    timeout: 2592000
    store-type: none
  # Redis 配置
  redis:
    database: 4
    host: localhost
    port: 6379
    timeout: 5000
  #    password: 123456
  # rabbitmq 信息
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 阿里云对象存储
aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: xxxx
      keysecret: xxxx
      bucketname: xxxx
# 鱼聪明SDK
yuapi:
  client:
    access-key: xxx
    secret-key: xxxx
# 支付宝沙箱
pay:
  qrcodeurl: http://localhost:8103/api/alipay/tradeQuery?alipayAccountNo=%s
  alipay:
    APP_ID: xxxx
    APP_PRIVATE_KEY: xxx
    ALIPAY_PUBLIC_KEY: xxxxx